name: solid_software_test_task
description: "Test task for Solid software company"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.2.3 


flutter:
  uses-material-design: true
